/*
 * Copyright (c) 2014-2025 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP DatexII <https://github.com/OpenChargingCloud/WWCP_DatexII>
 *
 * Licensed under the Affero GPL license, Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/agpl.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#region Usings

using System.Xml.Serialization;

#endregion

namespace cloud.charging.open.protocols.DatexII.v3.Common
{

    /// <summary>
    /// Classification of the severity of faults.
    /// </summary>
    public enum FaultSeverities
    {

        /// <summary>
        /// The fault is of low severity and has only limited impact on the usability of the equipment or the value of the data generated by the equipment.
        /// </summary>
        [XmlEnum("low")]
        Low,

        /// <summary>
        /// The fault is of medium severity which will significantly limit the usability of the equipment or devalue the usefulness of the data generated by the equipment.
        /// </summary>
        [XmlEnum("medium")]
        Medium,

        /// <summary>
        /// The fault is of high severity which will render the equipment unusable or any data generated by the equipment to be of no value.
        /// </summary>
        [XmlEnum("high")]
        High,

        /// <summary>
        /// The fault is of unknown severity and its effect on the usability of the equipment or the usefulness of the data generated by the equipment cannot be assessed.
        /// </summary>
        [XmlEnum("unknown")]
        Unknown,

        [XmlEnum("_extended")]
        Extended

    }

}
